### ISSUE TITLE
Support SDF3 placeholder prefix/postfix option

### ISSUE THREAD

**Issue by Gohla** [metaborg/spoofax-pie#71]
In Spoofax 2, the placeholder characters that SDF3 generates for a grammar can be configured with:

```
language:
  sdf:
    placeholder:
      prefix: "$"
```

but this is not yet supported in Spoofax 3. We should add configuration options for this to `spoofaxc.cfg`
